[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm build"

[deploy]
startCommand = "pnpm start:railway"
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 15
restartPolicyMaxRetries = 5
numReplicas = 1
sleepApplication = false
region = "us-west-1"

[deploy.envs]
NODE_ENV = "production"
PORT = "$PORT"
TZ = "UTC"
DAEMON_PROCESS = "true" 